apiVersion: v1
kind: Service
metadata:
  name: product-inventory-management
  labels:
    app: product-inventory-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: product-inventory-management