apiVersion: v1
kind: Service
metadata:
  name: transport-supply-management
  labels:
    app: transport-supply-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: transport-supply-management