---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-delivery-management
  labels:
    app: order-delivery-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-delivery-management
  template:
    metadata:
      labels:
        app: order-delivery-management
    spec:
      containers:
        - name: order-delivery-management
          image: username/order-delivery-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-inventory-management
  labels:
    app: product-inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-inventory-management
  template:
    metadata:
      labels:
        app: product-inventory-management
    spec:
      containers:
        - name: product-inventory-management
          image: username/product-inventory-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: transport-supply-management
  labels:
    app: transport-supply-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transport-supply-management
  template:
    metadata:
      labels:
        app: transport-supply-management
    spec:
      containers:
        - name: transport-supply-management
          image: username/transport-supply-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: order-delivery-management
  labels:
    app: order-delivery-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: order-delivery-management


---


apiVersion: v1
kind: Service
metadata:
  name: product-inventory-management
  labels:
    app: product-inventory-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: product-inventory-management


---


apiVersion: v1
kind: Service
metadata:
  name: transport-supply-management
  labels:
    app: transport-supply-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: transport-supply-management

